AWSTemplateFormatVersion: 2010-09-09
Description: Simple AWS Glue Job Deployment (No Parameters)

Resources:
  SimpleGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: simple-glue-job
      Role: arn:aws:iam::330084888881:role/GlueJobRole1725
      Command:
        Name: glueetl
        ScriptLocation: s3://aira1725/jobs/my_glue_script.py
        PythonVersion: 3
      DefaultArguments:
        "--TempDir": s3://aira1725/temp/
        "--job-language": python
        "--SOURCE_S3": s3://aira1725/source/
        "--TARGET_S3": s3://aira1725/target/
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
