name: Deploy AWS Glue Job

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      S3_BUCKET_NAME: aira1725
      SOURCE_S3: s3://aira1725/source/
      TARGET_S3: s3://aira1725/target/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::330084888881:role/GitHubActionsGlueDeployRole
        aws-region: us-east-1

    - name: Upload Glue script to S3
      run: |
        aws s3 cp scripts/my_glue_script.py s3://$S3_BUCKET_NAME/jobs/

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/glue-job.yaml \
          --stack-name simple-glue-job-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            SourceS3=$SOURCE_S3 \
            TargetS3=$TARGET_S3
